config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  devise_for :users
  get 'pages/show'
  get '/language/es', to: "application#set_english", as: 'set_english'
  get '/language/en', to: "application#set_spanish", as: 'set_spanish'
  get '/schedule/new/:clinic_id', to: "schedules#new"
  get '/login', to: 'users#sign_in', as: 'login'
  post '/signin', to: 'users#sign_in', as: 'signin'
  get '/register', to: 'users#sign_up', as: 'register'
  post '/register', to: 'users#confirm_registration', as: 'confirm_registration'
  
  get '/clinics/confirm/:id', to: 'clinics#confirm'

  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/profile', to: 'users#index', as: 'profiles'

  get '/find', to: 'schedules#index', as: 'find'
  post '/search_appointments', to: 'schedules#find', as: 'search_appointments'

  get '/review/new/:clinic_id', to: 'reviews#new', as: 'new_clinic_review'
  resources :reviews
  resources :clinics
  post '/clinics/:id/approve', to: 'clinics#approve', as: 'approve_clinic'

  post '/helpful/add/:review_id/:user_id', to: 'reviews#add_helpful', as: 'add_helpful'
  post '/helpful/remove/:review_id/:user_id', to: 'reviews#remove_helpful', as: 'remove_helpful'
  post '/unhelpful/add/:review_id/:user_id', to: 'reviews#add_unhelpful', as: 'add_unhelpful'
  post '/unhelpful/remove/:review_id/:user_id', to: 'reviews#remove_unhelpful', as: 'remove_unhelpful'

  root "pages#show", page: "home"

end

app/models/clinic.rb
require 'textacular/searchable'

class Clinic < ActiveRecord::Base

  belongs_to :user
  has_many :schedules
  has_many :reviews, dependent: :destroy
  before_save :review_average


  filterrific(
  default_filter_params: {},
  available_filters: [
    :search_query,
    :by_state,
    :by_municipality
  ]
  )
  #Required fields for possible filters
  validates :name, presence: { message: 'Name field required for clinic'}
  validates :state, presence: { message: 'State field required for clinic'}
  validates :municipality, presence: { message: 'Municipality field required for clinic'}
  # :nocov:
  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 3
    where(
      terms.map {
        or_clauses = [
          "LOWER(clinics.name) LIKE ?",
          "LOWER(clinics.state) LIKE ?",
          "LOWER(clinics.municipality) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }
  #For state filter
  scope :by_state, lambda { |state|
    where("state LIKE ?", "%#{state}%")
  }
  #For municipality filter
  scope :by_municipality, lambda { |municipality|
    where("municipality LIKE ?", "%#{municipality}%")
  }
  #For name filter
  scope :by_name, lambda { |name|
    where("name LIKE ?", "%#{name}%")
  }
  scope :order_by_name, -> {
    order(:name => :desc)
  }
  # :nocov:
 def self.options_for_select_state
  order('LOWER(state)').group('clinics.id', 'clinics.state', 'state').map { |e| [e.state, e.state] }
 end
 def self.options_for_select_municipality
  order('LOWER(municipality)').group('clinics.id', 'clinics.municipality', 'municipality').map { |e| [e.municipality, e.municipality] }
 end
 
 extend Searchable(:state)

 
 def review_average()

    if self.reviews.length == 0
        self.average_review = -1
    else
        total = 0
        self.reviews.each do |review|
            if review.rating
                total += review.rating
            end
        end
        self.average_review = total.to_f / self.reviews.length
    end


 end

end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy, :approve]
  before_action :authenticate_user!, except: [:index, :show, :confirm]

  # GET /clinics
  # GET /clinics.json
  def index
    @filterrific = initialize_filterrific(
    Clinic,
    params[:filterrific],
    select_options: {
        by_state: Clinic.options_for_select_state,
        by_municipality: Clinic.options_for_select_municipality
      },
    ) or return

    @clinics = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
    
  end

  
  # GET /clinics/1
  # GET /clinics/1.json
  def show
    
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
    @clinic = Clinic.find(params[:id])
  end

  # POST /clinics
  # POST /clinics.json
  def create
    params[:clinic][:pending] = true
    @clinic = Clinic.new(clinic_params)
    if @clinic.save
      redirect_to clinics_path
    else
      render :new
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    if @clinic.update(clinic_params)
      redirect_to @clinic
    else
      render :edit
    end
  end

  def confirm
      @clinic = Clinic.find_by_id(params[:id])
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url, notice: 'Clinic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /clinics/1/approve
  def approve
      @clinic.pending = false
      @clinic.save!
      redirect_to request.referer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

 

    # Never trust parameters from the scary internet, only allow the white list through.
    def clinic_params
      params.require(:clinic).permit(:name, :phone_number, :email, :website, :state, :municipality, :pending)
    end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.erb
<%= form_for @clinic do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
      <% @clinic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group label-floating">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group label-floating">
    <%= f.label :phone_number, class: "control-label"  %>
    <%= f.text_field :phone_number, class: "form-control"  %>
  </div>
  <div class="form-group label-floating">
    <%= f.label :email, class: "control-label"  %>
    <%= f.email_field :email, class: "form-control"  %>
  </div>
  <div class="form-group label-floating">
    <%= f.label :website, class: "control-label"  %>
    <%= f.text_field :website, class: "form-control"  %>
  </div>
  <div class="form-group label-floating">
    <%= f.label :state, class: "control-label"  %>
    <%= f.text_field :state, class: "form-control"  %>
  </div>
  <div class="form-group label-floating">
    <%= f.label :municipality, class: "control-label"  %>
    <%= f.text_field :municipality, class: "form-control"  %>
  </div>
  <div class="form-group label-floating">
    <%= f.label :latitude, class: "control-label" %>
    <%= f.text_field :latitude, class: "form-control" %>
  </div>
  <div class="form-group label-floating">
    <%= f.label :longitude, class: "control-label"  %>
    <%= f.text_field :longitude, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/clinics/_list.html.erb
<div id="filterrific_results">

  <h1>
    <%=  page_entries_info @clinics %>
  </h1>

  <div class="row">
    <% count = 1 %>
    <% @clinics.each do |clinic| %>
      <% if (current_user and current_user.admin) or not clinic.pending %>
      <div class="col-sm-6 col-md-6">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h2 class="panel-title"><%= link_to(clinic.name, clinic_path(clinic), { :class=>"" }) %></h2>
          </div>
          <div class="panel-body">
            <div id="radial<%= clinic.id %>" class="radial-container">
            </div>
            <ul>
              <% if clinic.phone_number and clinic.phone_number != "" %>
              <li>
                <span class="card-info-description"><%=I18n.t('.list.phone')%></span>
                <span class="card-info-value"><%= clinic.phone_number %></span>
              </li>
              <% end %>
              <% if clinic.email and clinic.email != "" %>
              <li>
                <span class="card-info-description"><%= I18n.t('.list.email')%></span>
                <span class="card-info-value"><%= link_to_unless(clinic.email.nil?, clinic.email, "mailto:#{clinic.email}", target: "_blank") %></span>
              </li>
              <% end %>
              <% if clinic.website and clinic.website != "" %>
              <li>
                <span class="card-info-description"><%= I18n.t('.list.website')%></span>
                <span class="card-info-value"><%= link_to_unless(clinic.website.nil?, clinic.website, "http://#{clinic.website}", target: "_blank") %></span>
              </li>
              <% end %>
              <% if clinic.state and clinic.state != "" %>
              <li>
                <span class="card-info-description"><%= I18n.t('.list.state')%></span>
                <span class="card-info-value"><%= clinic.state %></span>
              </li>
              <% end %>
              <% if clinic.municipality and clinic.municipality != "" %>
              <li>
                <span class="card-info-description"><%= I18n.t('.list.muni')%></span>
                <span class="card-info-value"><%= clinic.municipality %></span>
              </li>
              <% end %>
              <li>
                <span class="card-info-description"><%= I18n.t('.list.avg')%></span>
                <% if clinic.review_average == -1.0 %>
                  <span class="card-info-value"><%= I18n.t('.list.nor')%></i></span>
                <% else %>
                  <span class="card-info-value"><%= clinic.review_average %> <i>(<%= clinic.reviews.length %> reviews)</i></span>
                <% end %>
              </li>
            </ul>
            <br />
            
            <div class="row">
              <div class="col-sm-6 col-md-4">
                <%= link_to clinic, { :class=>"btn btn-raised btn-success" } do %>
                  <%= I18n.t('.list.view')%> <div class="ripple-container"></div>
                <% end %>
              </div>

              <% if current_user and current_user.clinics_id != clinic.id %>
                <div class="col-sm-6 col-md-4">
                <%= link_to new_clinic_review_path(clinic), { :class=>"btn btn-raised btn-info" } do %>
                  <%= I18n.t('.list.write')%> <div class="ripple-container"></div>
                <% end %>
                </div>
              <% end %>

              <% if current_user and current_user.clinics_id and current_user.clinics_id == clinic.id %>
                <div class="col-sm-6 col-md-4">
                  <%= link_to edit_clinic_path(clinic), { :class=>"btn btn-raised btn-info" } do %>
                    <%= I18n.t('.list.edit')%> <div class="ripple-container"></div>
                  <% end %>
                </div>

                <div class="col-sm-6 col-md-4">
                  <%= link_to clinic, class: "btn btn-raised btn-danger", method: :delete, data: { confirm: I18n.t('.list.confirm') }  do %>
                    <%= I18n.t('.list.delete')%> <div class="ripple-container"></div>
                  <% end %>
                </div>
              <% end %>

              <% if current_user and current_user.admin and clinic.pending %>
                  <%= link_to "/clinics/#{clinic.id}/approve", class: "btn btn-raised btn-success", method: :post, data: { confirm: 'Are you sure?' }  do %>
                    Confirm <div class="ripple-container"></div>
                  <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% if count % 2 == 0 %>
        <div class="clearfix hidden-xs"></div>
      <% end %>
      <% count = count + 1 %>
      <% end %>
    <% end %>
  </div>
</div>
<%=  will_paginate @clinics %>

app/views/clinics/confirm.html.erb
<h1><%= I18n.t('.confirm.header')%><%= @clinic.name %>?</h1>

<%= form_tag("/clinics/#{@clinic.id}", method: "delete") do%>
    
    <%= submit_tag(I18n.t('.confirm.tag')) %>

<% end %>

<!-- <%= button_to I18n.t('.confirm.cancel'), "/clinics/#{@clinic.id}", method: "get" %> -->
<%= link_to I18n.t('.confirm.cancel'), "/clinics/#{@clinic.id}/edit" %>

app/views/clinics/edit.html.erb
<div class="container-actions">
	<div class="btn-group-sm left-button back-button">
		<%= link_to clinic_path(@clinic.id), { :class=>"btn btn-primary btn-fab" } do %>
          <i class="material-icons">arrow_back</i><div class="ripple-container"></div>
        <% end %>
	</div>

</div>

<div class="well clinic-card edit-mode">
  <div class="panel-body left-info-container">
    <h1><%= I18n.t('edit.editing')%> <%= @clinic.name %></h1>
    <p class="error-message"><%= flash[:warning] %></p> <!-- For showing errors -->
    <%= render 'form' %>

    <%= form_tag("/clinics/confirm/#{@clinic.id}", method: "get") do %>
	    <%= submit_tag I18n.t('.edit.delete'), class: "btn btn-danger" %>
	<% end %>
  </div>
  <figure id="map" class="right-info-container map-container"></figure>
</div>

<script>
 $("#map").geolocateMap({
      markers: 
        [ 
          {"lat":"<%= @clinic.latitude  %> ", "lng":"<%= @clinic.longitude  %>" }
      ],
      google_maps: {
        zoom: 10
      },
      markers_settings: {
        draggable: false,
        animation: google.maps.Animation.DROP
      }
    })

</script>

app/views/clinics/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= I18n.t('.index.header')%></h1>
 <%= form_for_filterrific @filterrific do |f| %>
  <div class="container-fluid">
    <div class="jumbotron row clinics-search">
      <div class="form-group">
        <%= I18n.t('.index.search')%>
        <%= f.text_field(
          :search_query,
          class: 'filterrific-periodically-observed',
          class: "form-control col-lg-8", id: "search_field"
        ) %>
      </div>
      <div class="form-group">
        <%= I18n.t('.index.state')%>
        <%= f.select(
          :by_state,
          @filterrific.select_options[:by_state],
          { include_blank: '- Any -' },
          class: 'filterrific-periodically-observed',
          class: "form-control"
        ) %>
      </div>
      <div class="form-group">
        <%= I18n.t('.index.muni')%>
        <%= f.select(
          :by_municipality,
          @filterrific.select_options[:by_municipality],
          { include_blank: '- Any -' },
          class: 'filterrific-periodically-observed',
          class: "form-control"
        ) %>
      </div>
      <div >
        <%= link_to reset_filterrific_url, { :class=>"btn btn-warning" } do %>
          <%= I18n.t('.index.reset')%> <div class="ripple-container"></div>
        <% end -%>

        <!-- this button is just to improve the UX, simulates the search that is made with ajax-->
        <button class="btn btn-success" id="search_button"><%= I18n.t('.index.search')%><div class="ripple-container"></div></button>
      </div>
    </div>
  </div>
<%= render_filterrific_spinner %>
<% end %>
<% if current_user %>
<%= link_to new_clinic_path, { :class=>"btn btn-raised btn-success" } do %>  
    <%= I18n.t('.index.new')%> <div class="ripple-container"></div>
<% end %>
<% end %>
<%= render(
  partial: 'clinics/list',
  locals: { clinics: @clinics }
) %>

<%= javascript_tag do %>
  window.clinics = <%=raw @clinics.to_json %>;
<% end %>

<script type="text/javascript">
  $(function() {
    console.log(window.clinics);

    for (i = 0; i < window.clinics.length; i += 1) {
      clinic = window.clinics[i];
      console.log(clinic)
      divId = "radial" + clinic.id;
      // console.log("Constructing Radial for " + divId);

      percentage = 0
      if (clinic.average_review != -1) {
        percentage = (clinic.average_review / 5) * 100
      }
      
      radialProgress(document.getElementById(divId))
                .label(I18n.t('.index.avg'))
                .diameter(150)
                .value(percentage)
                .render();
    }
  })
</script>

app/views/clinics/index.js.erb
<% js = escape_javascript(
  render(partial: 'clinics/list', locals: { clinics: @clinics })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/clinics/new.html.erb
<h1><%= I18n.t('.new.header') %></h1>

<%= render 'form' %>

<%= link_to 'Back', clinics_path %>

app/views/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-actions">
  <div class="btn-group-sm left-button back-button">
    <%= link_to clinics_path, { :class=>"btn btn-primary btn-fab" } do %>
      <i class="material-icons">arrow_back</i><div class="ripple-container"></div>
    <% end %>
  </div>
</div>

<div class="well clinic-card">
  <div class="panel-body left-info-container card-to-edit">
    <h1 class="title-w-edit"><%= @clinic.name %></h1>
    <ul>
      <li>
        <span class="card-info-description"><%= I18n.t('.show.phone')%></span>
        <span class="card-info-value"><%= @clinic.phone_number %></span>
      </li>
      <li>
        <span class="card-info-description"><%= I18n.t('.show.email')%></span>
        <span class="card-info-value"><%= link_to_unless(@clinic.email.nil?, @clinic.email, "http://#{@clinic.email}", target: "_blank") %></span>
      </li>
      <li>
        <span class="card-info-description"><%= I18n.t('.show.website')%></span>
        <span class="card-info-value"><%= link_to_unless(@clinic.website.nil?, @clinic.website, "http://#{@clinic.website}", target: "_blank") %></span>
      </li>
      <li>
        <span class="card-info-description"><%= I18n.t('show.state')%></span>
        <span class="card-info-value"><%= @clinic.state %></span>
      </li>
      <li>
        <span class="card-info-description"><%= I18n.t('show.muni')%></span>
        <span class="card-info-value"><%= @clinic.municipality %></span>
      </li>
      <li>
        <span class="card-info-description">Average Rating</span>
        <% if @clinic.review_average == -1.0 %>
          <span class="card-info-value">No Reviews</i></span>
        <% else %>
          <span class="card-info-value"><%= @clinic.review_average %> <i>(<%= @clinic.reviews.length %> reviews)</i></span>
        <% end %>
      </li>
    </ul>
    <div>
      <% if current_user and current_user.clinics_id != @clinic.id %>
          <%= link_to "/review/new/#{@clinic.id}", { :class=>"btn btn-info " } do %>
            Add Review <div class="ripple-container"></div>
          <% end %>
      <% end %>

      <% if false and current_user and current_user.clinics_id == @clinic.id %>
          <%= link_to "/schedule/new/#{@clinic.id}", { :class=>"btn btn-success " } do %>
            <%= I18n.t('.show.schedule') %><div class="ripple-container"></div>
          <% end %>
      <% end %>
    </div>
    <% if current_user and current_user.admin %>
    <!-- positioned absolute -->
    <div class="btn-group-sm edit-button">
      <%= link_to edit_clinic_path(@clinic), { :class=>"btn btn-info btn-fab" } do %>
        <i class="material-icons">edit</i><div class="ripple-container"></div>
      <% end %>
    </div>
    <% end %>
  </div>
  <figure id="map" class="right-info-container map-container"></figure>
</div>

<script>
 $("#map").geolocateMap({
      markers: 
        [ 
          {"lat":"<%= @clinic.latitude  %> ", "lng":"<%= @clinic.longitude  %>" }
      ],
      google_maps: {
        zoom: 10
      },
      markers_settings: {
        draggable: false,
        animation: google.maps.Animation.DROP
      }
    })

</script>

<h1><%= I18n.t('.show.review.title')%></h1>
<div class="row">
<% count = 1 %>
<% @clinic.reviews.order("percent_helpful DESC").each do | review | %>
  <div class="col-sm-6 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-body card-to-edit">
        <h2><%= review.title %></h2>
        <ul>
          <li>
            <span class="card-info-description"><%= I18n.t('.show.review.rating')%></span>
            <span class="card-info-value"><%= review.rating %></span>
          </li>
          <li>
            <span class="card-info-description"><%= I18n.t('.show.review.comment')%></span>
            <span class="card-info-value"><%= review.body %></span>
          </li>
          <li>
            <span class="card-info-description"><%= I18n.t('.show.review.help')%></span>
            <span class="card-info-value">
                <% if review.helpfulness and review.total_ratings and review.total_ratings > 0 %>
                    <%= review.helpful %> <%= I18n.t('.show.review.of')%> <% review.total_ratings %> <%= I18n.t('.show.review.user')%>
                <% else %>
                    <%= I18n.t('.show.review.nodisplay')%>
                <% end %>
            </span>
            <% if current_user %>
            <span class="card-info-value">
                <i><%= I18n.t('.show.review.helpq')%></i><br />
                <% if review.user_voted(current_user.id) == 1 %>

                    <%= form_tag "/helpful/remove/#{review.id}/#{current_user.id}", class: "helpfulness-button" do %>
                        <% submit_tag  I18n.t('.show.review.y'), class: "btn btn-success" %>
                    <% end %>
                    <%= form_tag "/unhelpful/add/#{review.id}/#{current_user.id}", class: "helpfulness-button" do %>
                        <% submit_tag "No", class: "btn btn-secondary" %>
                    <% end %>

                <% elsif review.user_voted(current_user.id) == -1 %>

                    <%= form_tag "/helpful/add/#{review.id}/#{current_user.id}", class: "helpfulness-button" do %>
                        <% submit_tag "Yes", class: "btn btn-secondary" %>
                    <% end %>
                    <%= form_tag "/unhelpful/remove/#{review.id}/#{current_user.id}", class: "helpfulness-button" do %>
                        <% submit_tag "No", class: "btn btn-danger" %>
                    <% end %>

                <% else %>

                    <%= form_tag "/helpful/add/#{review.id}/#{current_user.id}", class: "helpfulness-button" do %>
                        <% submit_tag "Yes", class: "btn btn-secondary" %>
                    <% end %>
                    <%= form_tag "/unhelpful/add/#{review.id}/#{current_user.id}", class: "helpfulness-button" do %>
                        <% submit_tag "No", class: "btn btn-secondary" %>
                    <% end %>
                <% end %>
            </span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <% if count % 2 == 0 %>
    <div class="clearfix hidden-xs"></div>
  <% end %>
  <% count = count + 1 %>
<% end -%>
</div>