config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  devise_for :users
  get 'pages/show'
  get '/language/es', to: "application#set_english", as: 'set_english'
  get '/language/en', to: "application#set_spanish", as: 'set_spanish'
  get '/schedule/new/:clinic_id', to: "schedules#new"
  get '/login', to: 'users#sign_in', as: 'login'
  post '/signin', to: 'users#sign_in', as: 'signin'
  get '/register', to: 'users#sign_up', as: 'register'
  post '/register', to: 'users#confirm_registration', as: 'confirm_registration'
  
  get '/clinics/confirm/:id', to: 'clinics#confirm'

  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/profile', to: 'users#index', as: 'profiles'

  get '/find', to: 'schedules#index', as: 'find'
  post '/search_appointments', to: 'schedules#find', as: 'search_appointments'

  get '/review/new/:clinic_id', to: 'reviews#new', as: 'new_clinic_review'
  resources :reviews
  resources :clinics
  post '/clinics/:id/approve', to: 'clinics#approve', as: 'approve_clinic'

  post '/helpful/add/:review_id/:user_id', to: 'reviews#add_helpful', as: 'add_helpful'
  post '/helpful/remove/:review_id/:user_id', to: 'reviews#remove_helpful', as: 'remove_helpful'
  post '/unhelpful/add/:review_id/:user_id', to: 'reviews#add_unhelpful', as: 'add_unhelpful'
  post '/unhelpful/remove/:review_id/:user_id', to: 'reviews#remove_unhelpful', as: 'remove_unhelpful'

  root "pages#show", page: "home"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :clinics
  has_many :reviews
  has_one :info

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name()
    if self.first_name and self.last_name
        return self.first_name + " " + self.last_name 
    elsif self.first_name
        return self.first_name
    elsif self.last_name
        return self.last_name
    else
        return ""
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #GET index
    def index
        @users = User.all
    end

    # def check_params(id)
    #     if id == -1
    #         @prev_user = nil
    #     else
    #         @prev_user = User.find_by_id(id)
    #     end

    #     error_list = create_error_list
    #     error_message = create_error_message(error_list)
    #     return error_message
    # end
    
    # def create_error_message(error_list)
    #     if error_list.sum == 0
    #         error_message = "None"
    #     else
    #         error_message = "Error: "
    #         archive_error = ["First name field required; ", "Last name field required; ", 
    #             "Email field required; ", "Password field required; "]
    #         counter = 1
    #         error_list.each do |error| 
    #             error_message += archive_error[(error-1)]
    #         end
    #     end
    #     return error_message
    # end
    
    # def create_error_list
    #     error_list = [0]
    #     param_list = ["first_name", "last_name", "email", "password"]
        
    #     counter = 1
    #     param_list.each do |field| 
    #         error_val = field_check(field, counter)
    #         if error_val != -1
    #             error_list.push(error_val)
    #         end
    #         counter += 1
    #     end
    #     return error_list
    # end
    
    # def field_check(field, error_no)
    #     if params[:user][field] == ""
    #         if @prev_user
    #             params[:user][field] = @prev_user[field]
    #         end
    #         return error_no
    #     end
    #     return -1
    # end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    # def user_params
    #   params.require(:user).permit(:first_name, :last_name, :email, :password, :admin)
    # end

    #GET show
    def show
        id = params[:id]
        @user = User.find_by(id: id)

        if not @user
            flash[:warning] = "Unable to find user"
            redirect_to '/' and return
        else
            clinic_id = @user.clinics_id
            @clinic = Clinic.find_by(id: clinic_id)
            @reviews = @user.reviews 
        end

    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<p id="notice">Notice: <%= notice %></p>
<h1>Editing User</h1>

<p>Warning: <%= flash[:warning] %></p>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table-striped table-hover col-lg-12">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', "/profile/#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_registration_path %>

app/views/users/login.html.erb
<div class="col-md-4 center-block">
    <h1 class="text-center"> Login </h1>
    
    <%= flash[:warning] %>
    
    <form class="form-horizontal">
    <%= form_tag signin_path do %>
    <div class="form-group">
        <%= label_tag(:email, I18n.t('.user.login.email')) %>
        <%= email_field(:user, :email, id: "Email", :class => "form-control") %>
    </div>
    <div class="form-group">
        <%= label_tag(:password, I18n.t('.user.login.password')) %>
        <%= password_field(:user, :password, id: "Password", :class => "form-control") %>
    </div>
    
    <div class="form-group">
        <%= submit_tag I18n.t('.user.login.submit'), :class => "btn btn-default" %>
     </div>
    <% end %>
    </form>
    
    <h4><%= I18n.t('.user.login.notmember')%> <%= link_to I18n.t('.user.login.register'), register_path %></h4>
</div>

app/views/users/new.html.erb
<h1><%= I18n.t('user.new.new')%></h1>

<%= flash[:warning] %>

<%= render 'form' %>

<%= link_to I18n.t('user.new.back'), users_path %>

app/views/users/register.html.erb
<h1> <%= I18n.t('user.register.header')%> </h4>

<%= flash[:warning] %>

<%= render 'form' %>
<!-- <%= form_tag '/users' do %>
    <%= label_tag(:first_name, I18n.t('user.register.first')) %>
    <%= text_field_tag(:first_name, :class => "form-control") %>

    <%= label_tag(:last_name, I18n.t('user.register.last')) %>
    <%= text_field_tag(:last_name, :class => "form-control") %>

    <%= label_tag(:email, I18n.t('user.register.email')) %>
    <%= text_field_tag(:email, :class => "form-control") %>

    <%= label_tag(:password, I18n.t('user.register.password')) %>
    <%= text_field_tag(:password, :class => "form-control") %>

    <%= label_tag(:confirm_password, I18n.t('user.register.pconfirm')) %>
    <%= text_field_tag(:confirm_password, :class => "form-control") %>

    <%= submit_tag(I18n.t('user.register.register'), :class => "btn btn-default") %>
<% end %> -->

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well clinic-card" style="height: <%= 400 + (((@reviews.length + 1) / 2).ceil * 440) %>px">
  <div class="panel-body left-info-container card-to-edit" style="width: 100%;">
    <h1 class="title"><%= I18n.t('user.show.welcome')%> <%= @user.full_name %></h1>
    <ul>
      <li>
        <span class="card-info-description"><%= I18n.t('user.show.gender')%></span>
        <span class="card-info-value"><%= @user.gender %></span>
      </li>
      <li>
        <span class="card-info-description"><%= I18n.t('user.show.email')%></span>
        <span class="card-info-value"><%= link_to_unless(@user.email.nil?, @user.email, "http://#{@user.email}", target: "_blank") %></span>
      </li>
    </ul>
    <div>
      <div style="display: inline-block">
      <%= link_to edit_user_registration_path, { :class=>"btn btn-info " } do %>
        <%=I18n.t('user.show.editp')%> <div class="ripple-container"></div>
      <% end %>
      </div>
      <div style="display: inline-block">
      <% if @clinic and @clinic != "" %>
          <%= link_to clinic_path(@clinic), { :class=>"btn btn-success " } do %>
            <%=I18n.t('user.show.manage') + " #{@clinic.name} " %> <div class="ripple-container"></div>
          <% end %>
      <% end %>
      </div>
      <div style="display: inline-block">
      <%= form_tag destroy_user_session_path, method: 'delete' do %>
       <%= submit_tag("Log Out", class: "btn btn-warning") %>
      <% end %>
      </div>
    </div>
  </div>

  <h2 class="title"><%=I18n.t('user.show.yrev')%></h2>
  <div class="row">
    <% count = 1 %>
    <% @reviews.each do |review|%>
      <div class="col-sm-6 col-md-6">
        <div class="panel panel-primary">
          <div class="panel-body card-to-edit" style="width: 100%;">
            <h2 class="title-w-edit"><%= review.title %></h2>
            <ul>
              <li>
                <span class="card-info-description"><%=I18n.t('user.show.rating')%></span>
                <span class="card-info-value"><%= review.rating %></span>
              </li>
              <li>
                <span class="card-info-description"><%=I18n.t('user.show.comments')%></span>
                <span class="card-info-value"><%= review.body %></span>
              </li>
              <li>
                <span class="card-info-description"><%=I18n.t('user.show.helpfulness')%></span>
                <span class="card-info-value">
                  <% if review.helpfulness %>
                    <%= review.helpfulness %>
                  <% else %>
                    0
                  <% end -%>
                </span>
              </li>
            </ul>
            <% if current_user.id == review.user_id %>
              <div class="row">
                <div class="col-sm-6 col-md-4">
                  <%= link_to review, class: "btn btn-raised btn-danger", method: :delete, data: { confirm: I18n.t('user.show.confirm') }  do %>
                    <%=I18n.t('user.show.delete')%> <div class="ripple-container"></div>
                  <% end %>
                </div>
              </div>
              <div class="btn-group-sm edit-button">
                <%= link_to edit_review_path(review), { :class=>"btn btn-info btn-fab" } do %>
                  <i class="material-icons">edit</i><div class="ripple-container"></div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% if count % 2 == 0 %>
        <div class="clearfix hidden-xs"></div>
      <% end %>
      <% count = count + 1 %>
    <% end -%>
    </div>
</div>

app/views/users/signin.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('.user.signin.first')%></strong>
  <%= @user.first_name %>
</p>

<p>
  <strong><%= I18n.t('.user.signin.last')%></strong>
  <%= @user.last_name %>
</p>

<p>
  <strong><%= I18n.t('.user.signin.email')%></strong>
  <%= @user.email %>
</p>

<p>
  <strong><%= I18n.t('.user.signin.admin')%></strong>
  <%= @user.admin %>
</p>

<%= link_to I18n.t('.user.signin.edit'), edit_user_path(@user) %> |
<%= link_to I18n.t('.user.signin.back'), users_path %>