config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  devise_for :users
  get 'pages/show'
  get '/language/es', to: "application#set_english", as: 'set_english'
  get '/language/en', to: "application#set_spanish", as: 'set_spanish'
  get '/schedule/new/:clinic_id', to: "schedules#new"
  get '/login', to: 'users#sign_in', as: 'login'
  post '/signin', to: 'users#sign_in', as: 'signin'
  get '/register', to: 'users#sign_up', as: 'register'
  post '/register', to: 'users#confirm_registration', as: 'confirm_registration'
  
  get '/clinics/confirm/:id', to: 'clinics#confirm'

  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/profile', to: 'users#index', as: 'profiles'

  get '/find', to: 'schedules#index', as: 'find'
  post '/search_appointments', to: 'schedules#find', as: 'search_appointments'

  get '/review/new/:clinic_id', to: 'reviews#new', as: 'new_clinic_review'
  resources :reviews
  resources :clinics
  post '/clinics/:id/approve', to: 'clinics#approve', as: 'approve_clinic'

  post '/helpful/add/:review_id/:user_id', to: 'reviews#add_helpful', as: 'add_helpful'
  post '/helpful/remove/:review_id/:user_id', to: 'reviews#remove_helpful', as: 'remove_helpful'
  post '/unhelpful/add/:review_id/:user_id', to: 'reviews#add_unhelpful', as: 'add_unhelpful'
  post '/unhelpful/remove/:review_id/:user_id', to: 'reviews#remove_unhelpful', as: 'remove_unhelpful'

  root "pages#show", page: "home"

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.date_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.date_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :treatment_options %><br>
    <%= f.text_field :treatment_options %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/find.html.erb
<h4>Appointments Matching Your Search</h4>

<% if @appointments.length == 0 %>
    <p>Sorry, no appointments currently exist to fill your needs</p>
<% else %>
    <% @appointments.each do |appointment| %>
        <tr>
            <td><%= appointment.start_time %></td>
            <td><%= appointment.end_time %></td>
            <td><%= Clinic.find_by(id: appointment.the_clinic).municipality %></td>
            <td><%= Clinic.find_by(id: appointment.the_clinic).state %></td>
            <td><%= appointment.treatment_options %></td>
        </tr>
    <% end %>
<% end %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schedules</h1>

<table class="table-striped table-hover col-lg-12">
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Treatment options</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
    <tr>
      <td><%= schedule.start_time %></td>
      <td><%= schedule.end_time %></td>
      <td><%= schedule.treatment_options %></td>
      <td><%= link_to 'Show', schedule %></td>
      <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
      <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br/>
<br/>

<%= form_tag search_appointments_path, method: 'post', class: 'form-inline' do %>
  <div class="form-group">
    <%= label_tag :date %> 
    <%= datetime_field :search, :date, id: "date"%>
  </div>
  <div class="form-group">
    <%= label_tag :city %>
    <%= text_field_tag :city%>
  </div>
  <div class="form-group">
    <%= label_tag :municipality %>
    <%= text_field_tag :municipality %>
  </div>
  <div class="form-group">
    <%= label_tag :state %>
    <%= text_field_tag :state %>
  </div>
  <div class="form-group">
    <%= label_tag :reason %>
    <%= text_field_tag :reason %>
  </div>
  <%= submit_tag "Find Appointment" %>

<% end %>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @schedule.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @schedule.end_time %>
</p>

<p>
  <strong>Treatment options:</strong>
  <%= @schedule.treatment_options %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= form_for @schedule, method: :delete do |f| %>
	<% f.submit "Delete" %>
<% end %>
<%= link_to 'Back', schedules_path %>