config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  devise_for :users
  get 'pages/show'
  get '/language/es', to: "application#set_english", as: 'set_english'
  get '/language/en', to: "application#set_spanish", as: 'set_spanish'
  get '/schedule/new/:clinic_id', to: "schedules#new"
  get '/login', to: 'users#sign_in', as: 'login'
  post '/signin', to: 'users#sign_in', as: 'signin'
  get '/register', to: 'users#sign_up', as: 'register'
  post '/register', to: 'users#confirm_registration', as: 'confirm_registration'
  
  get '/clinics/confirm/:id', to: 'clinics#confirm'

  get '/profile/:id', to: 'users#show', as: 'profile'
  get '/profile', to: 'users#index', as: 'profiles'

  get '/find', to: 'schedules#index', as: 'find'
  post '/search_appointments', to: 'schedules#find', as: 'search_appointments'

  get '/review/new/:clinic_id', to: 'reviews#new', as: 'new_clinic_review'
  resources :reviews
  resources :clinics
  post '/clinics/:id/approve', to: 'clinics#approve', as: 'approve_clinic'

  post '/helpful/add/:review_id/:user_id', to: 'reviews#add_helpful', as: 'add_helpful'
  post '/helpful/remove/:review_id/:user_id', to: 'reviews#remove_helpful', as: 'remove_helpful'
  post '/unhelpful/add/:review_id/:user_id', to: 'reviews#add_unhelpful', as: 'add_unhelpful'
  post '/unhelpful/remove/:review_id/:user_id', to: 'reviews#remove_unhelpful', as: 'remove_unhelpful'

  root "pages#show", page: "home"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
  <title>Espolea</title>
  <script src="https://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--<a class="navbar-brand" href="#">Find My Clinic</a>-->
          <%= link_to I18n.t('.application.title'), root_path, :class => 'navbar-brand' %>
        </div>
        
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        
            <li> <%= link_to I18n.t('.application.clinic'), clinics_path %></li>
            <li> <%= link_to I18n.t('.application.review'), reviews_path %></li>
            <!-- 
            <li><%= link_to I18n.t('.application.schedule'), find_path %></li> 
            -->
        </ul> 

        <ul class="nav navbar-nav navbar-right">
            <% if session[:locale] == 'en' || session[:locale] == nil%>
              <button type="button" class="btn btn-raised btn-success">
                <%= link_to "Español", set_spanish_path %>
              </button>
            <% else %>
              <button type="button" class="btn btn-raised btn-success">
                <%= link_to "English", set_english_path %>
              </button>
            <% end %>
            
            <% if current_user == nil %>
                <button type="button" class="btn btn-default navbar-btn">
                    <%= link_to I18n.t('.application.login'), new_user_session_path %>
                </button>
            <% else %>
                <li> <%= link_to(I18n.t('.application.welcome') + "#{current_user.email}", "/profile/#{current_user.id}", class: "styled-submit") %></li>
            <% end %>
        </ul>
    </div>
    </div>
</nav>

<div class="container">
<%= yield %>
</div>

<script>
  $.material.init();
</script>

</body>
</html>